# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'jsonEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QApplication

class TextEd(QtWidgets.QTextEdit):
    
    def __init__(self, parent):
        QtWidgets.QTextEdit.__init__(self, parent)
    
    def wheelEvent(self, event):
        pass

class Main(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.setObjectName("MainWindow")
        self.resize(800, 600)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())

        self.setSizePolicy(sizePolicy)

        self.MainUi = QtWidgets.QWidget(self)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MainUi.sizePolicy().hasHeightForWidth())

        self.MainUi.setSizePolicy(sizePolicy)
        self.MainUi.setObjectName("MainUi")

        self.TextEditor = TextEd(self.MainUi)
        self.TextEditor.setGeometry(QtCore.QRect(35, 0, 765, 542))

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(100)
        sizePolicy.setHeightForWidth(self.TextEditor.sizePolicy().hasHeightForWidth())

        self.TextEditor.setSizePolicy(sizePolicy)
        self.TextEditor.setStyleSheet("font-size: 18px;")
        self.TextEditor.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.TextEditor.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.TextEditor.setObjectName("TextEditor")

        self.LineNumbers = QtWidgets.QScrollArea(self.MainUi)
        self.LineNumbers.setGeometry(QtCore.QRect(0, 0, 35, 542))
        self.LineNumbers.setStyleSheet("border: 0;\n" "max-width: 35px;")
        self.LineNumbers.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LineNumbers.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.LineNumbers.setWidgetResizable(True)
        self.LineNumbers.setObjectName("LineNumbers")

        self.ScrollArea = QtWidgets.QWidget()
        self.ScrollArea.setGeometry(QtCore.QRect(0, 0, 35, 542))
        self.ScrollArea.setObjectName("ScrollArea")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.ScrollArea)
        self.verticalLayout.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")

        self.LineNumbersList = []

        self.LineNumbers.setWidget(self.ScrollArea)

        self.setCentralWidget(self.MainUi)
        self.statusbar = QtWidgets.QStatusBar(self)
        self.statusbar.setObjectName("statusbar")

        self.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(self)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 30))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")

        self.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(self)
        self.actionOpen.setObjectName("actionOpen")

        self.actionNew = QtWidgets.QAction(self)
        self.actionNew.setObjectName("actionNew")

        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionNew)

        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.TextEditor.textChanged.connect(self.newLine)
        self.TextEditor.verticalScrollBar().valueChanged.connect(self.autoScroll)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionNew.setText(_translate("MainWindow", "New"))
    
    def resizeEvent(self, event):
        rect = self.size()
        self.TextEditor.resize(rect.width()-36, rect.height()-58)
        self.LineNumbers.resize(35, rect.height()-58)
        self.ScrollArea.resize(35, rect.height()-58)
    
    def autoScroll(self):
        scroll = self.TextEditor.verticalScrollBar()
        self.LineNumbers.verticalScrollBar().setValue(scroll.value())
    
    def newLine(self):
        numLines = self.TextEditor.toPlainText().count("\n")

        if numLines >= len(self.LineNumbersList):
            _translate = QtCore.QCoreApplication.translate
            self.LineNumbersList.append(QtWidgets.QPushButton(self.ScrollArea))
            self.LineNumbersList[numLines].setStyleSheet("margin: 0;\n" "height: 24px;")
            self.LineNumbersList[numLines].setObjectName("LineNumber")

            count = self.verticalLayout.count()

            self.verticalLayout.removeItem(self.verticalLayout.itemAt(count-1))

            self.verticalLayout.addWidget(self.LineNumbersList[numLines])

            spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)

            self.verticalLayout.addItem(spacerItem)
            
            self.LineNumbersList[numLines].setText(_translate("MainWindow", str(numLines+1)))


if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)

    m = Main()

    m.show()
    sys.exit(app.exec_())